### ISSUE TITLE
Starting CK conversion

### ISSUE THREAD

**Issue by fvella** [ctuning/ck-request-asplos18-mobilenets-tvm-arm#1]
## Requirements and Dependencies already provided by CK
 - [x] compiler-llvm-4.0.0-universal (ck-env)
``` $ ck install package:compiler-llvm-4.0.0-universal```
**FAILS on FireFly** Use the instruction below. 

 - [x] lib-openblas-0.2.18-universal
``` $ ck install package:lib-openblas-0.2.18-universal```
 - [x] lib-opencv-3.3.0
```$ ck install package:lib-opencv-3.3.0```
Failures  with gcc-5.4.1. **use** gcc-6.3.0
 - [x] lib-lapack-3.4.2
```$ ck install package:lib-lapack-3.4.2```
 - [x] lib-armcl-opencl-17.12
``$ ck install package:lib-armcl-opencl-17.12``
## Packages (to create)
 - [x] lib-blas
(see the comment below )
 - [x] nnvm 
 - [x] incubator-mxnet
See the comment 2 below.
## Programs
 - [x] acl_test 
 - [x] mali_imagenet_bench.py
 - [x] mxnet_test.py

## Dataset
 - [ ] ImageNet

**Comment by fvella** [comment]
New soft entry for blas has been created. 
```$ sudo apt-get install libblas*```

* To detect and register in ck :
``ck detect soft:lib.blas``

* To check the environment:
``$ ck show env --tags=blas,no-openblas``
  
``cfe1e23a4472bb1d   linux-32    32 BLAS library api-3    32bits,blas,blas,cblas,host-os-linux-32,lib,no-openblas,target-os-linux-32,v0,v0.3
``

**Comment by fvella** [comment]
## mxnet
* Get ck repo
 ``` $ ck pull repo:ck-mxne ```
* Follow the instruction: [here](https://github.com/ctuning/ck-mxnet)

**Comment by gfursin** [comment]
Seems that there is no mxnet package for ARM available via pip ... That's why version 0.11.0 (or any other) fails ...

**Comment by fvella** [comment]
@gfursin I confirm that! There is not mxnet package for ARM.

**Comment by gfursin** [comment]
We can later add custom.py in this package, check ARM target and fail nicely, but I don't have time for that right now ...

**Comment by fvella** [comment]
How to install **llvm** via apt and detecting via CK.
``` sudo apt-get install llvm-4.0 clang-4.0```
``` ck detect soft:compiler.llvm ```

**Comment by fvella** [comment]
All the packages and programs have been converted into ck... 
I am writing the ReadMe. After the test, I will close the issue.
