### ISSUE TITLE
Benchmark on Firefly-RK3399

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-request-asplos18-mobilenets-tvm-arm#5]
Now that we have the latest Firefly-RK3399 BSP ([xubuntu1604_201711301130](https://drive.google.com/drive/folders/1lbaR7XVyHT4SnXkJ2ybj5YXAzAjDBWfT)), we should record benchmarking results on this platform in the CK format.

**Comment by psyhtest** [comment]
As I understand from the README, we have three programs all using the same command key:
```
$ ck run program:tvm-arm  --cmd_key=all
$ ck run program:tvm-nnvm  --cmd_key=all
$ ck run program:tvm-mxnet --cmd_key=all
```
How about we perform and record the experiments as follows:
```
$ ck benchmark program:tvm-<program name> \
--cmd_key=all --repetitions=10 \
--record --record_repo=local \
--record_uoa=ck-request-asplos18-tvm-<program name>-<model name>-<precision> \ 
--tags=request,request-asplos18,tvm,<program name>,<model name>,<precision>
```
where:
- <program name> is one of `arm`, `nnvm`, `mxnet`;
- <model name> is one of `mobilenets`, `alexnet`, `vgg16`;
- <precision> is one of `fp32`, `fp16`.
(I'm writing this from memory so please correct me if I'm wrong.)

**Comment by gfursin** [comment]
Looks ok to me ;) ! Thanks! Just before taking off ;) ...

**Comment by fvella** [comment]
**Tvm** the support 

```
--model=[mobilenet || resnet18 || vgg16] --dtype=[float16 || float32]
```

**ARM**
ck run --cmd_key=run-net --env.CK_ACL_BACKEND=[cl || neon] --env.CK_ACL_MODEL=[mobilenet || vgg16] --env.CK_ACL_DTYPE=[float16 || float32] --env.CK_ACL_CONV_METHOD=[gemm || direct]


**Mxnet**
./mxnet_test.py --model=[mobilenet || resnet18 || vgg16]

**Comment by fvella** [comment]
List of Experiments:

```
<name><backend><model><data_type>
```

For example, for tvm we have a repetion tvm-tvm-mali. 


**MXNET**

```
mxnet-openblas-mobilenet-gemm-float32
mxnet-openblas-resnet18-gemm-float32
mxnet-openblas-vgg16-gemm-float32
```

**TVM**

```
tvm-tvm-mali-mobilenet-none-float16
tvm-tvm-mali-mobilenet-none-float32
tvm-tvm-mali-resnet18-none-float16
tvm-tvm-mali-resnet18-none-float32
tvm-tvm-mali-vgg16-none-float16
tvm-tvm-mali-vgg16-none-float32
```

**ARM**

```
armcl-cl-mobilenet-direct-float16
armcl-cl-mobilenet-direct-float32
armcl-cl-mobilenet-gemm-float16
armcl-cl-mobilenet-gemm-float32
armcl-cl-vgg16-direct-float16
armcl-cl-vgg16-direct-float32
armcl-cl-vgg16-gemm-float16
armcl-cl-vgg16-gemm-float32
armcl-neon-mobilenet-direct-float16
armcl-neon-mobilenet-direct-float32
armcl-neon-mobilenet-gemm-float16
armcl-neon-mobilenet-gemm-float32
armcl-neon-vgg16-direct-float16
armcl-neon-vgg16-direct-float32
armcl-neon-vgg16-gemm-float16
armcl-neon-vgg16-gemm-float32
```

**Comment by psyhtest** [comment]
Can you please attach here a zip of the experimental data when it's ready?

**Comment by fvella** [comment]
ARM experiment had some problem. I have to re-run just them.

**Comment by fvella** [comment]
I have the results. WRT to the list posted before we have less experiments. The application does not allow to run some of them. i.e. neon with fp16..

**Comment by fvella** [comment]
[request-tvm-firefly.zip](https://github.com/ctuning/ck-request-asplos18-mobilenets-tvm-arm/files/1841785/request-tvm-firefly.zip)

**Comment by gfursin** [comment]
Cool! Thanks a lot @fvella - I am now preparing presentations for tomorrow and if I find time, I will check it tonight ...

**Comment by gfursin** [comment]
I unified all experiments and recorded them in the CK format.
