### ISSUE TITLE
ARM inference time is higher with real images.

### ISSUE THREAD

**Issue by fvella** [ctuning/ck-request-asplos18-mobilenets-tvm-arm#6]
Following the issue on ARMComputeLibraty [here](https://github.com/ARM-software/ComputeLibrary/issues/381) there is a gap between the inference time on real images and random data.

**Comment by gfursin** [comment]
I reused real classification client for ArmCL from our [ReQuEST submission](https://github.com/dividiti/ck-request-asplos18-mobilenets-armcl-opencl) for the scoreboard, so I close this ticket.
