### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by fvella** [ctuning/ck-request-asplos18-mobilenets-tvm-arm#7]
In order to provide the same information of the other artifact would be great having the accuracy over real images for all the programs evaluated (MxNet, TVM, ARMCL).
The issue is related to [issue#6](https://github.com/ctuning/ck-request-asplos18-mobilenets-tvm-arm/issues/6)

**Comment by gfursin** [comment]
I provided new clients which perform accuracy calculation on ImageNet.
